---
title: "Module 1: R Foundations"
output: 
    learnr::tutorial:
        progressive: false
runtime: shiny_prerendered
description: "add description"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(learnr)
library(dplyr)

```


# Learn R - For IO Psychs

## Welcome!

We strongly encourage you to create a quarto document alongside this tutorial to work through the problems. That way you can take notes an retain your knowledge.


<!-- ==============================NEXT TOPIC=============================== -->


## Introduction to R and RStudio and Quarto {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic


<!-- ==============================NEXT TOPIC=============================== -->

## R data types and structures {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Data manipulation with dplyr and tidyr {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Control structures and functions {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Basic data visualization with ggplot2 {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic
