---
title: "Module 5: Psychometrics in R"
output: 
    learnr::tutorial:
        progressive: true
runtime: shiny_prerendered
description: "learn the foundations of using psychometrics in R, including methods of quantifying reliability and validity, item analysis, and scale analysis"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(learnr)
library(dplyr)
library(readr)

#source(here::here("inst/tutorials/module_2/www/module_datasets.R"))
big5_data <- readr::read_csv(here::here("inst/extdata/big5_data.csv"))
tma_data <- readr::read_csv(here::here("inst/extdata/tma_data.csv"))
# gradethis_setup()
```
```

# learnrIO

## Lesson Overview
```{r, child="lessons/module_5_overview.qmd"}
``` 


<!-- ===========================

===NEXT TOPIC=============================== -->


## Topic {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic


<!-- ==============================NEXT TOPIC=============================== -->

## Topic {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Topic {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->
