---
title: "Topics covered"
---
#### Module 1: Introduction to Data Analytics & R Foundations
- Overview of data analytics in the IO Psych business context 
- Introduction to R, RStudio, and Quarto 
- Version control: Git and Github 
- Managing and organizing data 
- Importing and exporting data in R 
- R data types and structures 
- Data manipulation with the tidyverse 

#### Module 2: Data Preparation & Exploratory Data Analysis in R
- Data cleaning and preparation with tidyr and dplyr 
- Descriptive statistics and distributions 
- Basic data visualization with ggplot2 
- Intermediate visualization techniques with ggplot2 and plotly 

#### Module 3: Statistics & Regression Analysis in R
- Correlation and regression analysis 
- Hypothesis testing with statistical inference and confidence intervals 
- Logistic and Ordinal Regression 

#### Module 4: Psychometrics with R
- Introduction to psychometrics 
- Reliability (split-half and other forms of reliability, Crohnbach's alpha, McDonald's omega) 
- Item analysis (item difficulty, item-total correlation, etc.) 
- Factor Analysis 
- Item Response Theory (IRT) 

#### Module 5: Advanced Topics in Data Analytics with R
- Text Mining and Natural language processing with tm and tidytext 
- Intro to Supervised Learning in R: Logistic Regression 
- Organizational network analysis with igraph and ggraph 
