---
title: "Module 4: HR Analytics with R"
output: 
    learnr::tutorial:
        progressive: true
runtime: shiny_prerendered
description: "add description"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(learnr)
library(dplyr)

```

# Learn R - For IO Psychs

## Welcome!

We strongly encourage you to create a quarto document alongside this tutorial to work through the problems. That way you can take notes an retain your knowledge.


<!-- ==============================NEXT TOPIC=============================== -->


## Introduction to HR analytics {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic


<!-- ==============================NEXT TOPIC=============================== -->

## Talent acquisition analysis {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Performance management analysis {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Employee engagement analysis {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic

<!-- ==============================NEXT TOPIC=============================== -->

## Workforce planning and forecasting {data-progressive=TRUE}

### Sub-topic 1 
this is a sub-topic

### Sub-topic 2 
This is another sub-topic
