---
title: "learnrIO: An Interactive R Programming and Statistics Course for Industrial Organizational Psychology Graduate and Undergraduate Students"
output: 
    learnr::tutorial:
        progressive: false
        css: css/preview-styles.css
        theme: "flatly"
runtime: shiny_prerendered
description: "A sneak peek into the R-based learning tutorial targeting Industrial Organizational Psychology graduate and undergraduate students, showcasing its purpose, vision, and topics covered in the course."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)

library(learnr)
library(tidyverse)
library(gradethis)

# devtools::load_all()
# employee_full_data <- learnrIO::employee_full_data
employee_full_data <- read_csv("/Users/macuser/Documents/Discord/datasets/employee_data.csv")

gradethis::gradethis_setup()

tutorial_options(
  exercise.completion = FALSE
)
```

## Introduction
```{r, child="sections/01_introduction.Rmd"}
```   


## What is R and Rstudio?
```{r, child="sections/02_what_is_R_Rstudio.Rmd"}
``` 


## Our Vision and Mission
```{r, child="sections/03_vision_mission.Rmd"}
``` 


## The Interactive Course
```{r, child="sections/04_the_interactive_course.Rmd"}
``` 

## Benefits
```{r, child="sections/05_benefits.Rmd"}
``` 

## Tutorial Preview

```{r, child="sections/06_tutorial_preview.Rmd"}
``` 


## Addressing the Challenges Faced by Professors
```{r, child="sections/07_addressing_challenges.Rmd"}
``` 

## Conclusion
```{r, child="sections/08_conclusion.Rmd"}
``` 


