---
title: "Lesson Overview"
---
### Welcome to **Module 1: Introduction to RStudio & Quarto!**  

In this lesson, we'll introduce you to R, RStudio, and Quarto. We'll start with the basics, showing you how to navigate and use R and RStudio. Then, we'll guide you on how to effectively leverage Quarto throughout these tutorials and beyond, enhancing your learning journey.\

This module's lessons are:  

- **Introduction to R and RStudio:** This lesson will provide an overview of RStudio, R, and Quarto, including how to download and install them. You will also learn the basics of R and RStudio, including how to navigate the RStudio interface, run code, and find help when you need it.  

- **Project Workflow and Reports using Quarto:** The final lesson will introduce you to the workflow of creating projects in RStudio and generating reports using Quarto. It will cover markdown basics, adding images and links, creating code chunks, understanding YAML, and knitting documents in different output formats.  


### Prerequisites

Before starting these lessons, you should have the latest release of R and RStudio installed on your computer. For this lesson, you should also have Quarto installed, which you can download [here](https://quarto.org/docs/get-started/).




###
Remember, learning is a journey. Don't worry if you don't grasp everything immediately. Practice and persistence are key.\

**Let's get started!**\
