---
title: "Introduction to R and RStudio"
---


### Introduction to the R language

R is a powerful programming language that was designed with statistics and data analysis in mind. It has a rich ecosystem of packages which can be utilized to perform complex data manipulations, analyses and visualizations. Moreover, it is highly extensible and allows you to integrate with other languages (like C++, Python, Julia, etc.) if needed.  


### Introduction to RStudio
   
RStudio is an integrated development environment (IDE) for R, providing a convenient and user-friendly interface for writing, running, and debugging R code. It includes several useful features such as syntax highlighting, code completion, and version control integration. RStudio makes working with R easier and more enjoyable. RStudio is often used by I/O psychology practitioners because it simplifies many of the technical aspects of coding, allowing practitioners to focus more on the insights gleaned from the data.  

It is quite possible you may be thinking, "so, what's the difference between R and RStudio? Aren't they the same thing?" Well, imagine R as a versatile and powerful kitchen appliance like a food processor, while RStudio is like a cookbook filled with recipes and step-by-step instructions on how to use the appliance.


[insert image]


R is the underlying programming language and software environment for statistical computing and graphics. It's like a food processor that can help you perform various tasks such as slicing, chopping, and blending ingredients. R is what allows you to perform data analysis, create visualizations, and develop statistical models.

On the other hand, RStudio is an integrated development environment (IDE) designed to work with R. It's like a cookbook that teaches you how to use the food processor (R) effectively, guiding you through the process of preparing a variety of dishes. RStudio provides features such as code editing, debugging, and project management, making it easier to write, run, and organize your R code.


[insert image]


### Navigating RStudio
Navigating RStudio is like learning the layout of a new office; you're more effective when you know where everything is and how it can help you. Let's take a look at the main components of RStudio.\

### The Four Main Panes

RStudio's interface is divided into four main panes, each with its own purpose.

###
**Source Pane**\
The upper-left pane by default is the Source Pane, your scripting playground. Here, you can write, edit, and organize your R scripts. RStudio aids your scripting with intuitive features like syntax highlighting, which helps differentiate commands, comments, and values with color codes, and code completion, a feature that predicts and suggests the function names as you type, reducing the likelihood to make errors.

[Placeholder for Image/GIF: Showing code typing and syntax highlighting in the Source Pane]

###
**Console Pane**\
The lower-left pane is the Console Pane, where the action happens! Here you can execute your R code. This can be done in two ways:\
- By typing code directly into the console which executes the code line by line.\
- Running a script from the Source pane. When you do this, the code copy-pastes into the Console pane.\
 
It's often better to write code in the Source Pane and then run it, so you have a record of your code. The console is where you'll see the results of your code, such as data frames, plots, and messages, as well as any errors with your code.\

[Placeholder for Image/GIF: Showing code execution in the Console Pane]

###
**Environment/History Pane**\
On the upper-right, we find the Environment/History Pane. The **Environment tab** is like your desk where all the current project's variables, data sets, and functions that you've created or loaded are displayed. Here, you can see at a glance all the objects that exist in your current R session. The **History tab** is your project diary; you can review all the commands that have been entered in the Console over time. It's valuable for revisiting previous work or correcting mistakes.\

[Placeholder for Image: Environment Tab showing list of variables and data sets]


###
**Files/Plots/Packages/Help Pane**\
The lower-right pane is the Files/Plots/Packages/Help Pane. This pane allows you to navigate your file system, see plots generated by your code, manage packages, and access R's built-in help system. This pane has multiple tabs:\
- **Files Tab:** This is your project folder navigator. Similar to a file explorer, it allows you to open, delete, move, and manage your files and folders.\
- **Plots Tab:** Here, you'll see the output of your graphical data representations, such as histograms or scatter plots.\
- **Packages Tab:** Your R toolbox. Install, view, and manage packages (collections of R functions, compiled code, and sample data).\
- **Help Tab:** Hover over this for R documentation and assistance with functions and packages.\
- **Viewer Tab:** Use this to view web content directly in RStudio, such as HTML content created through R Markdown or Shiny apps.\

[Placeholder for Image/GIF: Navigating through Files/Plots/Packages/Help/Viewer Pane]

### Setting Preferences
To make RStudio your own, go to `Tools -> Global Options`. You can select a theme that's easy on your eyes, change font size for readability, and even configure your workspace's default directory, so you always know where your projects are stored. Feel free to explore additional settings like code display options, including whether to show invisible characters or highlight matching parentheses.\

[Placeholder for Image: Global Options]

### Managing Files and RStudio Projects
RStudio makes it easy to manage your files and projects. You can create new files, open existing ones, and even create new RStudio Projects. A Project (note the uppercase "P") is a folder that contains all the files and data related to a specific analysis. It's a great way to keep your work organized and reproducible. You can create a new project by going to `File -> New Project`. You can also open an existing project by going to `File -> Open Project`.\

### Benefits of RStudio Projects
RStudio Projects are a an incredible tool for creating organized, reproducible workflows. Here are some of the benefits of using RStudio Projects:\

- **Organize Your Work:** Each project is like a separate digital folder for your R work. This keeps files for different projects from getting mixed up.\
Remember Your Settings: When you open a project, it remembers all your previous settings, like which files you had open, and where you left off.\
- **Manage Files Easily:** You can start a project in a new folder, in a folder where you already have some R files, or even from an online code repository like GitHub.\
- **You can have several RStudio Projects open at once:** Code executed in Project A does not have any effect on the R session and workspace of Project B.\

<div class="general-callout">
For more on RStudio Projects, check out the <a href="https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects">RStudio Projects Support Page</a>.
</div>

We'll revisit projects in more detail in the next lesson. For now, let's focus on the basics of R and RStudio.\


### Running Code in the Console
The Console is your chemistry lab for experimentation in R. It's where you write a command to get immediate results. Whether you're exploring data interactively or testing a quick fix, the Console Pane is where you want to be.\

###
**Running Code Line by Line**\
You can run code line by line by typing it directly into the Console. Let's try it out in your own RStudio console. Type `print("Hello, I/O Psychology!")` and press Enter. You should see the message "Hello, I/O Psychology!" printed in the Console. This is a great way to test out code and get immediate feedback.\

[Placeholder for Image/GIF: Running code line by line in the Console]

###
While the console is powerful for improvised work, remember that for larger or more structured analysis, scripting is better for maintaining reproducibility and clarity.\

In the next sections, we will delve into organizing your work through scripts and making the most out of RStudio's documentation resources.\


### Understanding the Environment Pane
The Environment Pane in RStudio can be thought of as your workspace's dashboard. It provides a real-time overview of the currently active objects within your R session. These objects could be anything from simple vectors to complex models you're using in your IO psychology research. Understanding and managing the Environment Pane is critical to keeping your analyses organized and efficient.\

###
When you open RStudio, the Environment Pane is typically empty, gradually filling up as you define variables and load datasets. It lists objects in alphabetical order, making it easy to find the data you're working with. The Environment Pane also shows the object type and structure, which provides a snapshot of your data's composition.\

[Placeholder for Image: Snapshot of the Environment Pane showing a list of variables and objects]

###
Let's create a simple vector and a data frame to see how they appear in the Environment pane. Paste the following code into the Console and press Enter to run it.\
 

```{r, eval=FALSE}
# a vector of employee ages
employee_ages <- c(25, 30, 35, 40)

# a data frame of employees
employees <- data.frame(
  id = 1:4,
  age = employee_ages,
  department = c("HR", "Marketing", "Sales", "IT")
)
```

After running the above code, you should see the `employee_ages` vector and the `employees` data frame appear in the Environment Pane. The `employee_ages` vector is listed under the "Values" section, while the `employees` data frame is listed under the "Data" section.\

Clicking on an object in the Environment Pane will open a new tab in the top-left pane, showing the object's contents. For example, if you click on the `employees` data frame, you'll see a preview of the data in the top-left pane. You can also click on the blue arrow next to the object name to see more details about the object, such as its dimensions of the data frame (4 rows and 3 columns) and the data types of each column.\

[Placeholder for Image: Data frame shown in the Environment Pane and structure in the Console Pane]

###
Let's assume we want to clean up our workspace by removing an outdated object. We can do this in at least two ways:\
- Using the `rm()` function to remove a single object. For example, `rm(employee_ages)` will remove the `employee_ages` vector from the workspace.\
- Using `rm(list = ls())` to remove all objects. This will remove all objects from the workspace, except for functions and packages.\
- Clicking the broom icon at the top of Environment Pane to clear all objects and functions. This is useful when you want to start fresh with a clean workspace.\


Use the `rm()` function to remove the `employee_ages` vector from the workspace. Then, click the broom icon to clear all remaining objects from the workspace. You should see the Environment Pane become empty again.\


### Getting Help

As you start your journey with R, you will undoubtedly encounter challenges or unfamiliar tasks. That's perfectly normal! One of the most important skills in programming, and especially in data analysis, is knowing how to find help when you need it. Let's explore some of the ways you can get help.  


### Using the Built-in R Help System

R has a built-in help system that you can access directly from RStudio. If you want to know more about a function, you can use the `help()` function or the `?` shortcut, followed by the name of the function. Hitting 'Enter' will launch the help documentation for the function you specify in the **Help Pane**, displaying detailed documentation that includes information on usage, arguments, details, and examples.\

Let's say you want to learn more about the `lm()` function, which is used to fit linear models. You can use the `help()` function or `?` shortcut to access the documentation. Try it out in the Console by typing `help(lm)` or `?lm` and pressing Enter. You should see the help documentation for the `lm()` function appear in the Help Pane.\

[Placeholder for Image: Help documentation for the `lm()` function]

###
Documentation for entire packages is also available. Say you are using the `ggplot2` package for data visualization and you want to access its user manual. You can do so by typing `help(package = "ggplot2")` and pressing Enter. This will open the package's help page in the Help Pane, providing detailed information about the package, including a description file, user guides (if any were created for the package), and list of all the functions it contains.\

Go ahead and try it out in the Console. Type `help(package = "ggplot2")` and press Enter. You should see the help documentation for the `ggplot2` package appear in the Help Pane. Briefly browse the included User Guides and Functions sections to get a sense of what's available.\

[Placeholder for Image: Help documentation for the ggplot2 package]


<div class="general-callout">
At the bottom of most help files are examples that show you how to use the function. Running these examples can be a great way to learn the functions' behavior and syntax.
</div>


### Online Resources

While the built-in help system is great for learning about specific functions, you will often encounter more complex problems or need broader advice. That's where online resources come in handy. Here are a few key ones:  

- **Google:** Don't underestimate the power of a well-phrased Google search! Often, someone else has already encountered the same problem and found a solution. Try to be as specific as possible in your search, and include "R" to get more relevant results.  

- **Stack Overflow:** This is a question-and-answer website for a wide range of programming topics, including R. You can search for your problem, and if it hasn't been asked before, you can post a new question. Remember to be specific and include a minimal reproducible example if possible.  

- **GitHub:** Many R packages are developed openly on GitHub, and you can often find help and examples in the repository's issues or wiki. If you think you've found a bug in a package, you can report it in the issues section.  

- **Package Documentation and Vignettes:** Most R packages come with detailed documentation and vignettes (long-form guides). You can access the documentation by using the `help()` function or `?`, and vignettes can be accessed with the `vignette()` function.  

- **R-Bloggers:** This is an aggregate of blogs about R, where you can find tutorials, examples, and advice on a wide range of topics. [R-bloggers website](https://www.r-bloggers.com/).  

- **Twitter:** Many R users and developers are active on Twitter, using the hashtag #rstats. It's a great place to ask questions, share your work, and keep up with the latest developments in the R community.  

- **Reddit:** The Reddit community can also be a helpful resource, particularly the r/rstats and r/RStudio subreddits. You can post questions, share your work, and engage in discussions with other R users. As with other online communities, try to be specific in your questions and provide a reproducible example if possible. Remember, the goal is to make it as easy as possible for others to understand your problem and provide help.\

- **ChatGPT:** When neither documentation nor online communities solve your issue, you can turn to AI-powered assistants like ChatGPT. These can help formulate questions that might be unclear or provide insights from a different perspective. When asking for help, be as specific as possible with your questions, providing context and any relevant code snippets. This will increase your chances of getting a helpful response.\


### Conclusion

Learning to effectively search for help and solutions online is a valuable skill that will greatly aid your journey into R and data analysis. The more you practice, the better you'll become at finding the information you need.\

Remember, everyone starts from scratch and it's okay not to know everything. The R community is known for being welcoming and helpful, so don't hesitate to ask questions when you're stuck!\

